#!/bin/bash

# Automatic Compilation

# # Introduction

# When a files changes in a repository that i'am interesting, automatic compile the nearest directory with pom in the project [tree](https://en.wikipedia.org/wiki/Tree_(data_structure)).

# ## Uses

# autoc <directory path>

# Results:
# - When a files changes in  <directory path>, it will recompile the nearest pom in the file directory structure beginning with <directory path>.

if [[ -n $(find -cmin -10 -name '*.java') ]]
then
	find -cmin -10 -name '*.java' | xargs realpath | xargs -I {} bash searchup -b {} -f pom.xml | xargs -I {} mvn -f {}/pom.xml install
else
	echo "No han habido cambios en los ultimos 10 minutos en ${PWD}."
fi
