#!/usr/bin/env bash

: '
- eml: extract eml all

- ripmime -i a.eml
  - produce tres archivos en que termina en 1 es el valido
  - ls | xargs -I {} ripmime -i {} -p {}  -d salida
  - ls *1
  -  mover esos archivos de salida para el directorio valido y ya esta.
'

ls *eml | xargs -I {} ripmime -i {} -p {}  -d salida

echo "run: 'ls *1' to list files with extracted content"
echo "run: 'rename_all' to remove .eml1 extention"