#!/usr/bin/env bash

cMonth=$(date +%m)
cDay=$(date +%d)
cYear=$(date +%Y)

rMonth=$(shuf -i $cMonth-12 -n 1)
rDay=$(shuf -i $cDay-27 -n 1)


echo https://calendar.google.com/calendar/u/0/r/day/$cYear/$rMonth/$rDay

