#!/usr/bin/env bash

: '
db: Cambia la base de datos.
'

# Uso env=des_sigef_1 ./switchdb
# Pero no usar directamente, config/switch-to-me, lo llama


CONFIG_HOME=/home/dvictoriano/devconfig/sigef

## Rutas Configuracion del Ambiente de Desarrollo SIGEF
## Estos son enlaces a los archivos actuales.
pom=${CONFIG_HOME}/actual/pom.xml
deployActual=${CONFIG_HOME}/actual/deployActual.sh
standalone=${CONFIG_HOME}/actual/standalone.xml

## Switch configuracion
printf "Opcion $env reemplazara Configuración del Ambiente de Desarrollo SIGEF actual. \n"

# Oportunidad para refactorizacion al poner todas las opciones en un areglo.

case $env in
  des_sigef_1)
	cat ${CONFIG_HOME}/des_sigef_1/pom.xml	       > ${pom}
	cat ${CONFIG_HOME}/des_sigef_1/deployActual.sh > ${deployActual}
	cat ${CONFIG_HOME}/des_sigef_1/standalone.xml  > ${standalone}
    ;;

  des_sigef_2)
	cat ${CONFIG_HOME}/des_sigef_2/pom.xml 		   > ${pom}
	cat ${CONFIG_HOME}/des_sigef_2/deployActual.sh > ${deployActual}
	cat ${CONFIG_HOME}/des_sigef_2/standalone.xml  > ${standalone}
    ;;

  des_sigef_3)
	cat ${CONFIG_HOME}/des_sigef_3/pom.xml 		   > ${pom}
	cat ${CONFIG_HOME}/des_sigef_3/deployActual.sh > ${deployActual}
	cat ${CONFIG_HOME}/des_sigef_3/standalone.xml  > ${standalone}
    ;;

  eme_sigef_1)
	cat ${CONFIG_HOME}/eme_sigef_1/pom.xml 		   > ${pom}
	cat ${CONFIG_HOME}/eme_sigef_1/deployActual.sh > ${deployActual}
	cat ${CONFIG_HOME}/eme_sigef_1/standalone.xml  > ${standalone}
    ;;

  *)
    printf "Opcion Configuracion desconocida. Validas (des_sigef_1, des_sigef_2, des_sigef_3, eme_sigef_1). \n"
    ;;
esac
