#!/usr/bin/env python3

import sys
import unidecode

'''
@dbremont / @dvictoriano
Remove accents

Example
unicode-normalize Málaga -> Malaga

Referece
https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-normalize-in-a-python-unicode-string
'''

'''
Requires: unidecode
'''

if len(sys.argv) != 2:
    print("Ussage: unicode-normalize <str>")
    sys.exit(0)

accented_string =  sys.argv[1]
unaccented_string = unidecode.unidecode(accented_string)
print(unaccented_string)
