#!/usr/bin/env bash

# echo $1 >> /home/dvictoriano/Code/Utils/out.txt

#xdotool search --name $1 windowfocus key "ctrl+c"
#xdotool search --name $1 windowfocus key "ctrl+l"

# xdotool search --name "$1" >>  /home/dvictoriano/Code/Utils/out.txt

# wmctrl -l >> /home/dvictoriano/Code/Utils/out.txt

id=$(wmctrl -l | grep -oP "(?<=)(0x\w+)(?=.*$1)")  # Put here the regex for the browser you use

echo $id

if [ -z ${id} ]; 
then 
	echo "Not Foundcat "
	#echo "Not Found [${1}]">> /home/dvictoriano/Code/Utils/out.txt	
	exit
else 
	# echo ${id} >> /home/dvictoriano/Code/Utils/out.txt
	xdotool key --window $id "ctrl+l"
	xdotool key --window $id "ctrl+c"
fi


# xdotool key --window 0x020003d6  "ctrl+L"
# xdotool key --window 0x020003d6  "ctrl+C"


